platform :ios, '8.0'
use_frameworks!

target 'Mini-Project' do
    pod 'BFPaperButton'
    pod 'HSDatePickerViewController'
    pod 'GoogleMaps'
    pod 'BSImagePicker'
    pod 'SwiftyDropbox'
    pod 'Font-Awesome-Swift'
end

