# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Travel Sticky' do
    pod 'BFPaperButton'
    pod 'HSDatePickerViewController'
    pod 'GoogleMaps'
    pod 'BSImagePicker'
    pod 'SwiftyDropbox'
    pod 'Font-Awesome-Swift'
end

